default: &default
  adapter: sqlserver
  host: localhost
  port: 1433
  username: sa
  password: Complex@123
  timeout: 5000
  pool: 5

development:
  <<: *default
  database: consumer_development

test:
  <<: *default
  database: consumer_test

production:
  <<: *default
  database: consumer_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
