development:
  clients:
    default:
      database: consumer_api_development
      hosts:
        - localhost:27017
      options:
        pool_size: 50
        timeout: 30
  driver_options:

test:
  clients:
    default:
      database: consumer_api_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1